version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:patch"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
